import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { cookies } from "next/headers";
import "./globals.css";
import Navbar from "./Navbar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import Headbar from "./Headbar";
import QueryClientProvider from "./QueryClientProvider";
import { Toaster } from "sonner";
import { BookmarkProvider } from "@/components/bookmarks/context";
import VibeKanbanCompanion from "./VibeKanbanCompanion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sidebarState = cookieStore.get("sidebar_state")?.value;
  const defaultOpen = sidebarState !== "false";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {process.env.NODE_ENV === "development" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
            data-enabled="true"
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <QueryClientProvider>
          <BookmarkProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              <Navbar variant="inset" />
              <SidebarInset>
                <Toaster richColors />
                <Headbar />
                <main className="flex min-w-0 flex-1 flex-col gap-4 p-4">
                  {children}
                </main>
              </SidebarInset>
            </SidebarProvider>
          </BookmarkProvider>
        </QueryClientProvider>
        <VibeKanbanCompanion />
      </body>
    </html>
  );
}
